7 спринт сохранение и чтение из файла
anna-tarusova/java-kanban pull request #2
Opened 2024-12-01 22:59 UTC by anna-tarusova

2024-12-03 06:26 UTC, VadimZharkov commented on src/ru/yandex/practicum/tasks/logic/InMemoryTaskManager.java
>          BaseTask copyTask = getCopyTask(task);
Не понятно для чего делается копирование, на мой взгляд лишняя операция.

2024-12-03 06:34 UTC, VadimZharkov commented on src/ru/yandex/practicum/tasks/model/BaseTask.java
> +            throw new ManagerLoadException("Неправильный формат данных");
Ожидается, что ManagerLoadException будет выбрасываться в классах менеджеров. Представим, что BaseTask fromString(String value) будет использоваться где-то кроме менеджеров и ManagerLoadException  будет уже не уместно. Здесь "красивей" выбросить стандартное IllegalStateException. В менеджере его перехватить и выбросить ManagerLoadException.

2024-12-03 06:37 UTC, VadimZharkov commented on src/ru/yandex/practicum/tasks/logic/FileBackedTaskManager.java
> +
Хорошо бы  здесь еще проставить значение счетчика идентификаторов максимальным значением из файла, чтобы при дальнейшем добавлении не возникло коллизий.

2024-12-03 06:39 UTC, VadimZharkov commented on src/ru/yandex/practicum/tasks/logic/FileBackedTaskManager.java
> +    public void add(Subtask subtask, int epicId) {
int epicId лишний параметр, у подзадачи же есть поле с идентификатором эпика, его и нужно использовать.

2024-12-03 06:39 UTC, VadimZharkov requested changes
Хорошая работа, можно улучшить.

2024-12-08 19:22 UTC, anna-tarusova commented on src/ru/yandex/practicum/tasks/logic/InMemoryTaskManager.java
>          BaseTask copyTask = getCopyTask(task);
Копирование нужно из-за ТЗ 6 спринта.<br>
Там написано: С помощью сеттеров экземпляры задач позволяют изменить любое своё поле, но это может повлиять на данные внутри менеджера. Протестируйте эти кейсы и подумайте над возможными вариантами решения проблемы.<br>
На это даже тесты есть.

2024-12-08 22:12 UTC, anna-tarusova commented on src/ru/yandex/practicum/tasks/model/BaseTask.java
> +            throw new ManagerLoadException("Неправильный формат данных");
Сделано как вы сказали

2024-12-09 05:54 UTC, VadimZharkov commented on src/ru/yandex/practicum/tasks/logic/InMemoryTaskManager.java
>          BaseTask copyTask = getCopyTask(task);
Но ты же не меняешь поля задачи при добавлении. Здесь копирование не нужно, достаточно написать тест, что при добавлении в менеджер задач поля исходного таска остались неизменными. 
Читаем ТЗ внимательно) Твоя ремарка про ТЗ относится не к менеджеру задач, а к менеджеру истории - "Отдельно протестируйте новую функциональность менеджера истории." И в реализации менеджера истории копирование тобой сделано совершенно верно.

2024-12-09 05:55 UTC, VadimZharkov approved these changes

2024-12-16 20:55 UTC, merged